sm6375-common: Add missing lib
error: vendor/motorola/sm6375-common/Android.bp:463:1: "audio.bluetooth_qti.default" depends on undefined module "libbluetooth_audio_session_qti_2_1".